// Generated by UPDATE_RENDERER_GOLDENS=1; review every changed value.
export const approvedRendererSnapshots = {
  "simple": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:a7a39b72f29718e653e73503210fbb59",
        "meta": {
          "fixture": "simple"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "like",
              "roles": {
                "experiencer": "user",
                "theme": "coffee"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "simple"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:a7a39b72f29718e653e73503210fbb59",
        "meta": {
          "fixture": "simple"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "like",
              "roles": {
                "experiencer": "user",
                "theme": "coffee"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "simple"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:a7a39b72f29718e653e73503210fbb59",
        "meta": {
          "fixture": "simple"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "like",
              "roles": {
                "experiencer": "user",
                "theme": "coffee"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "simple"
        }
      },
      "warnings": []
    }
  },
  "negated": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:d7d0cedf093f829955a2fa7f696d1b79",
        "meta": {
          "fixture": "negated"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "negated": true,
              "predicate": "accept",
              "roles": {
                "agent": "system",
                "theme": "token"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "negated"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:d7d0cedf093f829955a2fa7f696d1b79",
        "meta": {
          "fixture": "negated"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "negated": true,
              "predicate": "accept",
              "roles": {
                "agent": "system",
                "theme": "token"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "negated"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:d7d0cedf093f829955a2fa7f696d1b79",
        "meta": {
          "fixture": "negated"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "negated": true,
              "predicate": "accept",
              "roles": {
                "agent": "system",
                "theme": "token"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "negated"
        }
      },
      "warnings": []
    }
  },
  "conditions": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:562a77a7ae22fe1bb05561df5f820282",
        "meta": {
          "fixture": "conditions"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "conditions": [
                {
                  "predicate": "authenticate",
                  "roles": {
                    "agent": "user"
                  }
                },
                {
                  "predicate": "validate",
                  "roles": {
                    "subject": "token"
                  }
                }
              ],
              "predicate": "grant",
              "roles": {
                "agent": "system",
                "target": "access"
              }
            }
          ],
          "kind": "instruction",
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "conditions"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:562a77a7ae22fe1bb05561df5f820282",
        "meta": {
          "fixture": "conditions"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "conditions": [
                {
                  "predicate": "authenticate",
                  "roles": {
                    "agent": "user"
                  }
                },
                {
                  "predicate": "validate",
                  "roles": {
                    "subject": "token"
                  }
                }
              ],
              "predicate": "grant",
              "roles": {
                "agent": "system",
                "target": "access"
              }
            }
          ],
          "kind": "instruction",
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "conditions"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:562a77a7ae22fe1bb05561df5f820282",
        "meta": {
          "fixture": "conditions"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "conditions": [
                {
                  "predicate": "authenticate",
                  "roles": {
                    "agent": "user"
                  }
                },
                {
                  "predicate": "validate",
                  "roles": {
                    "subject": "token"
                  }
                }
              ],
              "predicate": "grant",
              "roles": {
                "agent": "system",
                "target": "access"
              }
            }
          ],
          "kind": "instruction",
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "conditions"
        }
      },
      "warnings": []
    }
  },
  "modality": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:e79c1315bab8f5677860dc2ccea3d1ac",
        "meta": {
          "fixture": "modality"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "modality": "possibility",
              "predicate": "rain",
              "roles": {}
            }
          ],
          "kind": "prediction",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "modality"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:e79c1315bab8f5677860dc2ccea3d1ac",
        "meta": {
          "fixture": "modality"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "modality": "possibility",
              "predicate": "rain",
              "roles": {}
            }
          ],
          "kind": "prediction",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "modality"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:e79c1315bab8f5677860dc2ccea3d1ac",
        "meta": {
          "fixture": "modality"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "modality": "possibility",
              "predicate": "rain",
              "roles": {}
            }
          ],
          "kind": "prediction",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "modality"
        }
      },
      "warnings": []
    }
  },
  "annotations": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:295df243c6a33994c30b6e16aea7ce61",
        "meta": {
          "fixture": "annotations"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "annotations": {
            "confidence": 0.95,
            "tags": [
              "ui"
            ]
          },
          "clauses": [
            {
              "predicate": "prefer",
              "roles": {
                "experiencer": "user",
                "theme": "dark_mode"
              }
            }
          ],
          "kind": "preference",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "annotations"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:295df243c6a33994c30b6e16aea7ce61",
        "meta": {
          "fixture": "annotations"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "annotations": {
            "confidence": 0.95,
            "tags": [
              "ui"
            ]
          },
          "clauses": [
            {
              "predicate": "prefer",
              "roles": {
                "experiencer": "user",
                "theme": "dark_mode"
              }
            }
          ],
          "kind": "preference",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "annotations"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:295df243c6a33994c30b6e16aea7ce61",
        "meta": {
          "fixture": "annotations"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "annotations": {
            "confidence": 0.95,
            "tags": [
              "ui"
            ]
          },
          "clauses": [
            {
              "predicate": "prefer",
              "roles": {
                "experiencer": "user",
                "theme": "dark_mode"
              }
            }
          ],
          "kind": "preference",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "annotations"
        }
      },
      "warnings": []
    }
  },
  "provenance": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:96d815328a42cb4ef89d5e0b7a1df6be",
        "meta": {
          "fixture": "provenance"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "state",
              "roles": {
                "source": "document",
                "theme": "fact"
              }
            }
          ],
          "kind": "fact",
          "provenance": {
            "author": "alice",
            "source": "manual"
          },
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "provenance"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:96d815328a42cb4ef89d5e0b7a1df6be",
        "meta": {
          "fixture": "provenance"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "state",
              "roles": {
                "source": "document",
                "theme": "fact"
              }
            }
          ],
          "kind": "fact",
          "provenance": {
            "author": "alice",
            "source": "manual"
          },
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "provenance"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:96d815328a42cb4ef89d5e0b7a1df6be",
        "meta": {
          "fixture": "provenance"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "state",
              "roles": {
                "source": "document",
                "theme": "fact"
              }
            }
          ],
          "kind": "fact",
          "provenance": {
            "author": "alice",
            "source": "manual"
          },
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "provenance"
        }
      },
      "warnings": []
    }
  },
  "metadata-rendering": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:b87ee9d1724b98f3b6da37affe3dca71",
        "meta": {
          "fixture": "metadata-rendering"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {
          "generic": {
            "code": "A(user,resource)",
            "profile": "generic",
            "tokens": 4
          }
        },
        "sem": {
          "annotations": {
            "confidence": 0.8
          },
          "clauses": [
            {
              "predicate": "access",
              "roles": {
                "agent": "user",
                "theme": "resource"
              }
            }
          ],
          "kind": "rule",
          "provenance": {
            "source": "spec"
          },
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "metadata-rendering"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:b87ee9d1724b98f3b6da37affe3dca71",
        "meta": {
          "fixture": "metadata-rendering"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {
          "generic": {
            "code": "A(user,resource)",
            "profile": "generic",
            "tokens": 4
          }
        },
        "sem": {
          "annotations": {
            "confidence": 0.8
          },
          "clauses": [
            {
              "predicate": "access",
              "roles": {
                "agent": "user",
                "theme": "resource"
              }
            }
          ],
          "kind": "rule",
          "provenance": {
            "source": "spec"
          },
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "metadata-rendering"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:b87ee9d1724b98f3b6da37affe3dca71",
        "meta": {
          "fixture": "metadata-rendering"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "annotations": {
            "confidence": 0.8
          },
          "clauses": [
            {
              "predicate": "access",
              "roles": {
                "agent": "user",
                "theme": "resource"
              }
            }
          ],
          "kind": "rule",
          "provenance": {
            "source": "spec"
          },
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "metadata-rendering"
        }
      },
      "warnings": [
        "Renderings removed"
      ]
    }
  },
  "long-role": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:9dc0222878cde72816d0bf3a95aaf539",
        "meta": {
          "fixture": "long-role"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "process",
              "roles": {
                "agent": "system",
                "subject": "An extremely long descriptive text that exceeds fifty characters and must be snapshotted"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "long-role"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:9dc0222878cde72816d0bf3a95aaf539",
        "meta": {
          "fixture": "long-role"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "process",
              "roles": {
                "agent": "system",
                "subject": "An extremely long descriptive text that exceeds fifty characters and must be snapshotted"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "long-role"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:9dc0222878cde72816d0bf3a95aaf539",
        "meta": {
          "fixture": "long-role"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "process",
              "roles": {
                "agent": "system",
                "subject": "An extremely long descriptive text that exceeds fifty characters and must be snapshotted"
              }
            }
          ],
          "kind": "fact",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "long-role"
        }
      },
      "warnings": []
    }
  },
  "references": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:07a0b0962107485c3c1375cffa0f2ed9",
        "meta": {
          "fixture": "references"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "see",
              "roles": {
                "agent": "reader",
                "theme": "doc"
              }
            }
          ],
          "kind": "instruction",
          "references": [
            {
              "ref": "docs",
              "type": "source",
              "value": "Manual"
            }
          ],
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "references"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:07a0b0962107485c3c1375cffa0f2ed9",
        "meta": {
          "fixture": "references"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "see",
              "roles": {
                "agent": "reader",
                "theme": "doc"
              }
            }
          ],
          "kind": "instruction",
          "references": [
            {
              "ref": "docs",
              "type": "source",
              "value": "Manual"
            }
          ],
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "references"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:07a0b0962107485c3c1375cffa0f2ed9",
        "meta": {
          "fixture": "references"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "see",
              "roles": {
                "agent": "reader",
                "theme": "doc"
              }
            }
          ],
          "kind": "instruction",
          "references": [
            {
              "ref": "docs",
              "type": "source",
              "value": "Manual"
            }
          ],
          "schema": "lunum-sem/0.1-draft",
          "world": "tool"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "references"
        }
      },
      "warnings": []
    }
  },
  "multiple-clauses": {
    "safe": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:e1b2c76b20915894a5e8d0343cd35d23",
        "meta": {
          "fixture": "multiple-clauses"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "like",
              "roles": {
                "experiencer": "alice",
                "theme": "coffee"
              }
            },
            {
              "predicate": "prefer",
              "roles": {
                "experiencer": "bob",
                "theme": "tea"
              }
            }
          ],
          "kind": "statement",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "multiple-clauses"
        }
      },
      "warnings": []
    },
    "short": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:e1b2c76b20915894a5e8d0343cd35d23",
        "meta": {
          "fixture": "multiple-clauses"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "like",
              "roles": {
                "experiencer": "alice",
                "theme": "coffee"
              }
            },
            {
              "predicate": "prefer",
              "roles": {
                "experiencer": "bob",
                "theme": "tea"
              }
            }
          ],
          "kind": "statement",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "multiple-clauses"
        }
      },
      "warnings": []
    },
    "tight": {
      "record": {
        "fingerprint": "lfp:0.1:sha256:e1b2c76b20915894a5e8d0343cd35d23",
        "meta": {
          "fixture": "multiple-clauses"
        },
        "policy": {
          "category": "test",
          "confidence": 1,
          "eligible": true,
          "reasons": [
            "golden"
          ],
          "risk": "low"
        },
        "recordVersion": "lunum-record/0.1-draft",
        "renderings": {},
        "sem": {
          "clauses": [
            {
              "predicate": "like",
              "roles": {
                "experiencer": "alice",
                "theme": "coffee"
              }
            },
            {
              "predicate": "prefer",
              "roles": {
                "experiencer": "bob",
                "theme": "tea"
              }
            }
          ],
          "kind": "statement",
          "schema": "lunum-sem/0.1-draft",
          "world": "real"
        },
        "source": {
          "language": "en",
          "ref": null,
          "role": "user",
          "text": "multiple-clauses"
        }
      },
      "warnings": []
    }
  }
} as const;
